import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import { SocialIcon } from 'react-social-icons';
import ThemeToggler from '@/companent/toggle';

const inter = Inter({ subsets: ['latin'] });

const data = "I specialize in coding the stuff that nobody sees, but everyone needs. I'm the unsung hero of your app";

export default function Home() {
  return (
    <>
      <Head>
        <title>Abdullah Gumus</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/avatar.svg' />
      </Head>

      <main className='font-kalam'>
        <div
          className='rowDiv flex flex-row items-center justify-evenly mt-5 
      
     

      '
        >
          <div className='footerName flex flex-row '>
            <h1 className='text-4xl md:text-2xl'>Abdullah</h1>{' '}
            <h1 className='text-4xl text-red-600	 ml-2 md:text-2xl'>Gümüş</h1>
          </div>

          <div className='ml-7 flex flex-row '>
            <ThemeToggler></ThemeToggler>
          </div>
        </div>
        <div className='flex flex-col items-center   w-screen'>
          <br></br>
          <br></br>
          <div className='boddy flex flex-col items-center justify-center w-1/4 gap-x-0.5	 gap-y-0 text-center		'>
            <div className='imageBOx'>
              <Image className='p-2' src='/avatar.svg' alt='Picture of the author' width={200} height={200}></Image>
            </div>
            <h1 className='text-4xl md:text-3xl'> {'Hi, Im Abdullah '}</h1>
            <br></br>
            <div className='flex flex-row'>
              <h1 className='text-3xl mr-2	md:text-3xl'>Backend </h1>
              <h1 className='text-3xl	text-red-700 md:text-3xl'> Developer</h1>
            </div>

            <br></br>
            <div className=' md:w-56 lg:w-96 '>
              <p className='md:text-m  '>{data}</p>
            </div>
          </div>
          <div className='Button  flex flex-row justify-evenly mt-7'>
            <SocialIcon
              className='transition ease-in-out delay-150  hover:scale-125 duration-75'
              label='2px'
              url='https://twitter.com/Apoles_py'
            ></SocialIcon>
            <div className='ml-3 transition ease-in-out delay-150  hover:scale-125 duration-75 '>
              <SocialIcon url='https://github.com/Apoles'></SocialIcon>
            </div>
            <div className='ml-3 transition ease-in-out delay-150  hover:scale-125 duration-75'>
              {' '}
              <SocialIcon url='https://www.instagram.com/abdullahgms_offical'></SocialIcon>
            </div>
            <div className='ml-3 transition ease-in-out delay-150  hover:scale-125 duration-75'>
              <SocialIcon url='https://www.linkedin.com/in/abdullah-gumus-91217a1b7'></SocialIcon>
            </div>
            <div className='ml-3 transition ease-in-out delay-150  hover:scale-125 duration-75'>
              <SocialIcon url='https://medium.com/@abdullahgumus'></SocialIcon>
            </div>
          </div>
          <p className='bottom-3 fixed'>© Abdullah Gümüş - 2023</p>
        </div>
      </main>
    </>
  );
}
