import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import { SocialIcon } from 'react-social-icons';
import ThemeToggler from '@/companent/toggle';
import Header from '@/companent/header';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

const data = "I specialize in coding the stuff that nobody sees, but everyone needs. I'm the unsung hero of your app";

export default function Home() {
  return (
    <>
      <Head>
        <title>Abdullah Gumus</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/avatar.svg' />
      </Head>

      <main className='font-kalam'>
        <Header></Header>
        <div className='flex flex-col items-center   w-screen'>
          <br></br>
          <br></br>
          <div className='boddy flex flex-col items-center justify-center w-1/4 gap-x-0.5	 gap-y-0 text-center		'>
            <div className='imageBOx'>
              <Image className='p-2' src='/avatar.svg' alt='Picture of the author' width={200} height={200}></Image>
            </div>
            <h1 className='text-4xl md:text-3xl'> {'Hi, Im Abdullah '}</h1>
            <br></br>
            <div className='flex flex-row'>
              <h1 className='text-3xl mr-2	md:text-3xl'>Backend </h1>
              <h1 className='text-3xl	text-red-700 md:text-3xl'> Developer</h1>
            </div>

            <br></br>
            <div className=' md:w-56 lg:w-96 '>
              <p className='md:text-m  '>{data}</p>
            </div>
          </div>
          <div className='Button  flex flex-row justify-evenly mt-7'>
            <SocialIcon
              target='_blank'
              className='transition ease-in-out delay-150  hover:scale-125 duration-75'
              label='2px'
              url='https://twitter.com/Apoles_py'
            ></SocialIcon>
            <div className='ml-3 transition ease-in-out delay-150  hover:scale-125 duration-75 '>
              <SocialIcon target='_blank' url='https://github.com/Apoles'></SocialIcon>
            </div>
            <div className='ml-3 transition ease-in-out delay-150  hover:scale-125 duration-75'>
              {' '}
              <SocialIcon target='_blank' url='https://www.instagram.com/abdullahgms_offical'></SocialIcon>
            </div>
            <div className='ml-3 transition ease-in-out delay-150  hover:scale-125 duration-75'>
              <SocialIcon target='_blank' url='https://www.linkedin.com/in/abdullah-gumus-91217a1b7'></SocialIcon>
            </div>
            <div className='ml-3 transition ease-in-out delay-150  hover:scale-125 duration-75'>
              <SocialIcon target='_blank' url='https://medium.com/@abdullahgumus'></SocialIcon>
            </div>
          </div>
          <div className='mt-7'>
            <Link href={'/resume'}>
              <button
                type='button'
                className='px-4 py-3 bg-gray-100 rounded-md hover:border-red-700 border-2  duration-500  cursor-pointer`     text-black  focus:ring-4 shadow-lg transform active:scale-x-75 transition-transform mx-5 flex'
              >
                <svg className='h-6 w-6' fill='none' viewBox='0 0 24 24' stroke='currentColor'>
                  <path
                    stroke-linecap='round'
                    stroke-linejoin='round'
                    stroke-width='2'
                    d='M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4'
                  />
                </svg>

                <span className='ml-2'>Go to resume</span>
              </button>
            </Link>
          </div>

          <p className='bottom-3 fixed'>© Abdullah Gümüş - 2023</p>
        </div>
      </main>
    </>
  );
}
