import Header from '@/companent/header';
import ThemeToggler from '@/companent/toggle';
import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
  return (
    <>
      <Head>
        <title>Abdullah Gumus</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/avatar.svg' />
      </Head>

      <main className='font-kalam'>
        <Header></Header>
        <br></br>

        <div className='mt-6 max-w-screen-lg md:flex mx-auto sm:flex sm:flex-col sm:items-center sm:justify-center sm:w-full'>
          <div className='md:w-1/3 p-2 relative sm:flex-col '>
            <div className='sm:flex sm:flex-col'>
              <div className=' sm:flex-col '>
                <img
                  className='h-32 w-32 rounded-full mx-auto '
                  src='https://avatars3.githubusercontent.com/u/59800600?s=460&amp;u=95f222387f598c85508c9b6d5d8662ebf4ae8b85&amp;v=4'
                />
                <div className='mb-12 text-center mt-4 justify-center items-center'>
                  <h1 className='text-2xl  text-gray-800 font-bold'>Abdullah Gümüş</h1>
                  <div className='md:text-lg text-gray-600'>Backend Developer</div>
                  <div className='text-gray-600 md:hidden mt-1'>abdullahgumus14@hotmail.com</div>
                </div>
              </div>
            </div>
          </div>
          <div className='md:w-2/3 p-2 w-full flex flex-col   '>
            <div className='flex flex-col items-center justify-center'>
              <br></br>
              <div className='mx-4 flex flex-col justify-center items-center  '>
                <h1 className='mb-4  text-4xl text-gray-700 font-bold'>Education</h1>
                <ul>
                  <li className='mb-4'>
                    <h2 className='text-2xl font-medium text-gray-800'>Sakarya Uygulamalı Bilimler Üniverstesi</h2>
                    <div className='mt-1'>
                      <div>
                        <p>Mekatronik Mühendisliği</p>
                        <i className='bx bx-calendar text-sm'></i>
                        <small className='text-sm text-gray-600'>01/09/2018 - Present </small>
                      </div>
                    </div>
                  </li>
                </ul>
                <br></br>

                <h1 className='mb-4 text-4xl text-gray-700 font-bold'>Experience</h1>
                <ul>
                  <li className='mb-4'>
                    <h2 className='text-2xl font-medium text-gray-800'>Stajyer Selective Yazılım</h2>
                    <div className='mt-1 space-y-1'>
                      <div>
                        <ul className='max-w-md space-y-1 text-gray-500 list-disc list-inside dark:text-gray-400'>
                          <li>HTML, CSS ve JavaScript kullanarak frontend geliştirme.</li>
                          <li>React kullanarak web uygulamaları oluşturma.</li>
                          <li>MongoDB kullanarak veritabanı işlemleri yapma.</li>
                        </ul>
                      </div>

                      <div>
                        <i className='bx bx-calendar text-sm'></i>
                        <small className='text-sm text-gray-600'>01.06.2020 - 31.08.2020 </small>
                      </div>
                    </div>
                  </li>

                  <li className='mb-4'>
                    <h2 className='text-2xl font-medium text-gray-800'>Backend Developer Akıl Fikir Mektebi</h2>
                    <div className='mt-1 space-y-1'>
                      <div>
                        <ul className='max-w-md space-y-1 text-gray-500 list-disc list-inside dark:text-gray-400'>
                          <li>Node. Js ve Nest. Js kullanarak API istekleri yazma.</li>
                          <li>PostreSQL kullanarak veritabanı işlemleri yapma.</li>
                          <li>MongoDB kullanarak veritabanı işlemleri yapma.</li>
                          <li>ZeptoMail servisi kullanma.</li>
                        </ul>
                      </div>

                      <div>
                        <i className='bx bx-calendar text-sm'></i>
                        <small className='text-sm text-gray-600'>01.10.2021 - 01.06.2022 </small>
                      </div>
                    </div>
                  </li>
                </ul>
                <br></br>
              </div>
            </div>
            <div className='mx-4'>
              <h1 className='mb-4 text-4xl text-gray-700 font-bold'>Skill</h1>
              <ul>
                <li className='mb-6 flex flex-wrap'>
                  <span className='mr-2 my-1 rounded-full border px-4 text-sm py-2 font-medium bg-gray-200'>Flask</span>
                  <span className='mr-2 my-1 rounded-full border px-4 text-sm py-2 font-medium bg-gray-200'>
                    Python Pandas
                  </span>
                  <span className='mr-2 my-1 rounded-full border px-4 text-sm py-2 font-medium bg-gray-200'>
                    ETL Automation
                  </span>
                  <span className='mr-2 my-1 rounded-full border px-4 text-sm py-2 font-medium bg-gray-200'>
                    Laravel/Lumen
                  </span>
                  <span className='mr-2 my-1 rounded-full border px-4 text-sm py-2 font-medium bg-gray-200'>
                    Composer Dependency
                  </span>
                  <span className='mr-2 my-1 rounded-full border px-4 text-sm py-2 font-medium bg-gray-200'>
                    Codeigniter
                  </span>
                  <span className='mr-2 my-1 rounded-full border px-4 text-sm py-2 font-medium bg-gray-200'>Slim</span>
                  <span className='mr-2 my-1 rounded-full border px-4 text-sm py-2 font-medium bg-gray-200'>
                    ExpressJS
                  </span>
                  <span className='mr-2 my-1 rounded-full border px-4 text-sm py-2 font-medium bg-gray-200'>
                    Code Principles
                  </span>
                  <span className='mr-2 my-1 rounded-full border px-4 text-sm py-2 font-medium bg-gray-200'>
                    Design Database
                  </span>
                  <span className='mr-2 my-1 rounded-full border px-4 text-sm py-2 font-medium bg-gray-200'>
                    Design Pattern
                  </span>
                  <span className='mr-2 my-1 rounded-full border px-4 text-sm py-2 font-medium bg-gray-200'>
                    System Analysis
                  </span>
                  <span className='mr-2 my-1 rounded-full border px-4 text-sm py-2 font-medium bg-gray-200'>VueJS</span>
                  <span className='mr-2 my-1 rounded-full border px-4 text-sm py-2 font-medium bg-gray-200'>
                    ReactJS
                  </span>
                  <span className='mr-2 my-1 rounded-full border px-4 text-sm py-2 font-medium bg-gray-200'>
                    Tailwind css/Bootstrap
                  </span>
                  <span className='mr-2 my-1 rounded-full border px-4 text-sm py-2 font-medium bg-gray-200'>
                    Sass/Scss
                  </span>
                  <span className='mr-2 my-1 rounded-full border px-4 text-sm py-2 font-medium bg-gray-200'>
                    Web Server
                  </span>
                  <span className='mr-2 my-1 rounded-full border px-4 text-sm py-2 font-medium bg-gray-200'>
                    Mail Server
                  </span>
                  <span className='mr-2 my-1 rounded-full border px-4 text-sm py-2 font-medium bg-gray-200'>
                    PostgreSQL
                  </span>
                  <span className='mr-2 my-1 rounded-full border px-4 text-sm py-2 font-medium bg-gray-200'>
                    Mysql/MariaDB
                  </span>
                  <span className='mr-2 my-1 rounded-full border px-4 text-sm py-2 font-medium bg-gray-200'>
                    MonggoDB
                  </span>
                  <span className='mr-2 my-1 rounded-full border px-4 text-sm py-2 font-medium bg-gray-200'>
                    Linux Sysadmin
                  </span>
                  <span className='mr-2 my-1 rounded-full border px-4 text-sm py-2 font-medium bg-gray-200'>
                    Networking
                  </span>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
